# Generated by Django 5.0.3 on 2024-03-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.CharField(max_length=4),
        ),
    ]
