Version: "3.8"

services:
  movies:
    build:
      context: ./app
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev
